### ISSUE TITLE
current_radius floating point error

### ISSUE THREAD

**Issue by cgyurgyik** [spherical-volume-rendering/algorithm-team-collaboration#14]
So in the following example,
```
  min_bound = [0.0, 0.0];
    max_bound = [30.0, 30.0];
    
    ray_origin = [3.0, 10.0];
    ray_direction = [2.3, 1.0];
    
    circle_center = [15.0, 15.0];
    circle_max_radius = 10.0;
    num_radial_sections = 6;
    num_angular_sections = 8;
    
    t_begin = 0.0;
    t_end = 10.0;
    
    verbose = true;
    
    [rVoxels, thetaVoxels] = polarCoordinateTraversal_old(min_bound, max_bound, ray_origin, ray_direction, circle_center, circle_max_radius, num_radial_sections, num_angular_sections, t_begin, t_end, verbose);
```
If you try to run it with our current version of ```polarCoordinateTraversal_old```,
it will stop at the origin.

Printing the variable ```cr``` (current radius) will yield a number similar to ```3.32e-34```.
I presume this is some floating point error. A simple fix for this might be:

Replace 
```if (cr == 0), cr = current_radius^2; end``` 
with
```if (abs(cr) < eps), cr = current_radius^2; end```

Let me know your thoughts either way.

**Comment by ak-2485** [comment]
Good fix. We should make sure all float comparisons are fixed similarly.
