### ISSUE TITLE
Issues when ray does not go through innermost radial voxel

### ISSUE THREAD

**Issue by cgyurgyik** [spherical-volume-rendering/algorithm-team-collaboration#15]
With this example:
```
    min_bound = [0.0, 0.0];
    max_bound = [30.0, 30.0];
    
    ray_origin = [3.0, 5.0];
    ray_direction = [2.3, 1.0];
    
    circle_center = [15.0, 15.0];
    circle_max_radius = 10.0;
    num_radial_sections = 3;
    num_angular_sections = 4;
    
    t_begin = 0.0;
    t_end = 10.0;
    
    verbose = true;
    
    [rVoxels, thetaVoxels] = polarCoordinateTraversal_old(min_bound, max_bound, ray_origin, ...
        ray_direction, circle_center, circle_max_radius, ...
        num_radial_sections, num_angular_sections, t_begin, t_end, verbose);
```

The ray does not go through the innermost radial voxel, the function ends early before traversal ends. This is because our hot fix ```jenkyR``` only goes into action when ```current_radius == 0```, a.k.a. when we go through the inner most radius.

In the example above,
The current radius ```cr``` is: 11.1111, and the intersection ```sect``` is 
```
   5.9777 - 1.1366i
   5.9777 + 1.1366i
```

Uh-oh. We need to generalize this so that our step switches even when we don't go through this voxel.

**Comment by cgyurgyik** [comment]
![Screen Shot 2020-02-25 at 9 42 27 PM](https://user-images.githubusercontent.com/37983775/75306699-c886f000-5817-11ea-9e52-427cd762bdaf.png)

**Comment by cgyurgyik** [comment]
Expensive solution:
1. Determine the t_ intersection at 
```(current_radius - delta_voxel)```, 
```(current_radius)```, 
```(current_radius + delta_voxel)```.
2. Find the smallest t_intersection that meets the following criteria:
- ``` t_intersection > t```
- ``` t_intersection is not imaginary.```

If none of these exist, we've exited our voxel.

**Comment by cgyurgyik** [comment]
Potential solution 2:

-Continue using ```jenkyR```. Re-name it to something more appropriate.
- During the initialization phase, determine the smallest radial voxel at which intersection occurs. This will allow us to then generalize ```jenkyR``` to cause the directional switch at a certain voxel rather than just then zero voxel.

**Comment by ak-2485** [comment]
Is this still a problem? I've completed the radial hit using dot product and this issue doesn't occur. Will PR.

**Comment by cgyurgyik** [comment]
Yep! I was going to write code to fix it in the next few hours, but if you have a better solution I'll be glad to look over that.

**Comment by cgyurgyik** [comment]
We can consider this fixed for now, but this leads us to other issues with the new dot product version.
