### ISSUE TITLE
Renaming files

### ISSUE THREAD

**Issue by ak-2485** [spherical-volume-rendering/algorithm-team-collaboration#16]
Let's rename files; something better than the _old append. I'll PR for a radial_hit_dotprod and polar_coordinate_traversal_dotprod. For the originals let's get rid of the _old and otherwise remain the same. Thoughts?

**Comment by cgyurgyik** [comment]
Agreed. I think whatever we're going to show Matt, let's call that polarCoordinateTraversal and radial_hit. The rest we can place in a separate folder with its main goal, i.e. ```_jenkyR```.

**Comment by cgyurgyik** [comment]
Resolved.
