### ISSUE TITLE
Reduce trigonometric calculations in angular_hit.

### ISSUE THREAD

**Issue by cgyurgyik** [spherical-volume-rendering/algorithm-team-collaboration#37]
During our presentation, Matt was asking about calls to expensive functions, and other optimizations we can conduct. Below I present an optimization in the ```angular_hit``` function. I confess I am hesitant to implement any optimizations yet, at least not until we have a working 3-dimensional implementation.

Right now in ```angular_hit```, we have the following:
```
delta_theta = 2 * pi / num_angular_sections;
interval_theta = [current_voxel_ID_theta * delta_theta, (current_voxel_ID_theta + 1) * delta_theta];

xmin = cos(min(interval_theta));
xmax = cos(max(interval_theta));
ymin = sin(min(interval_theta));
ymax = sin(max(interval_theta));

if (single(tan(min(interval_theta))) == ray_direction(2)/ray_direction(1) ...
        && single(tan(max(interval_theta))) == ray_direction(2)/ray_direction(1))
        fprintf("parallel");
        ...
end
```

In a single call to ```radial_hit```, this ends up being the following :
**function | #**
```cos``` | 2 calls
```sin``` | 2 calls
``` tan``` | 2 calls
We also calculate ```delta_theta``` (float multiplication, float division) and ```interval_theta``` (2 float multiplications).

Multiply this by N, where N is the number of angular section traversals.

We can reduce this to 1 by adding the following calculations to the initialization phase in ```polarCoordinateTraversal.m```:
```
delta_theta = 2 * pi / num_angular_sections;
interval_thetas = zeros(num_angular_sections);
interval_theta_cos = zeros(num_angular_sections);
interval_theta_sin = zeros(num_angular_sections);
interval_theta_tan = zeros(num_angular_sections);

% Calculate cosine min/max, sine min/max for angular sections.
for k = 1 : num_angular_sections
    i = (k - 1) * delta_theta;  % Recall: theta goes from 0 to N - 1, but MATLAB begins at 1.
    interval_thetas(k) = i;
    interval_theta_cos(k) = cos(i);
    interval_theta_sin(k) = sin(i);
    interval_theta_tan(k) = sin(i);
end
```

And then, in ```angular_hit```, we need only to reference these pre-calculated numbers:
```
% Note: must be careful about off-by-one error.
voxel_one = current_voxel_ID_theta + 1;
voxel_two = current_voxel_ID_theta + 2;
interval_theta = [interval_thetas(voxel_one), interval_thetas(voxel_two)];

xmin = min(interval_theta_cos(voxel_one),  interval_theta_cos(voxel_two));
xmax = max(interval_theta_cos(voxel_one),  interval_theta_cos(voxel_two));
ymin = min(interval_theta_sin(voxel_one),  interval_theta_sin(voxel_two));
ymax = max(interval_theta_sin(voxel_one),  interval_theta_sin(voxel_two));

y_over_x = ray_direction(2) / ray_direction(1);
is_parallel_min = single(min(interval_theta_tan(voxel_one), interval_theta_tan(voxel_two) )) == y_over_x;
is_parallel_max = single(max(interval_theta_tan[voxel_one], interval_theta_tan(voxel_two) )) == y_over_x;
if (is_parallel_min && is_parallel_max)
   fprintf("parallel\n");
   ...
end
```

This cuts out a lot of the meat in our hot loop (see exact numbers above), at the cost of a computationally more expensive start-up time. Given many rays, this will be worth it though.

With regards to ```atan2``` (asked about in the presentation), we call this once per ray in the initialization phase as well.

**Comment by matthewturk** [comment]
This seems reasonable; I'm not sure how to help more.

**Comment by ak-2485** [comment]
I think this is a  good approach! Can you add this to the polar traversal and rerun tests? Note that the tan business at the end of what you post is no longer used.

**Comment by cgyurgyik** [comment]
I'm going to leave this be for now since its an optimization I can implement at any time, but will just bloat our code.
