### ISSUE TITLE
XZ plane for Azimuthal Hit.

### ISSUE THREAD

**Issue by cgyurgyik** [spherical-volume-rendering/algorithm-team-collaboration#59]
https://github.com/spherical-volume-rendering/algorithm-team-collaboration/blob/4d4774b694a9f84e27060b31de3fc1a46adb917e/matlab/spherical-traversal/azimuthal_hit.m#L74

Should this be checking the z-direction() since we're now living in the XZ plane for azimuthal hit?

**Comment by ak-2485** [comment]
This is addressed in most recent merge
